/******************************************************************************/
/****     Generated by IBExpert 2015.12.21.1 25/02/2018 09:54:02 p. m.     ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

SET CLIENTLIB 'C:\AppData\fbclient.dll';

CREATE DATABASE 'C:\AppData\cobranza.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN BOOLEANO AS
SMALLINT
CHECK (VALUE = 0 OR VALUE = 1);

CREATE DOMAIN CADENA010 AS
VARCHAR(10);

CREATE DOMAIN CADENA050 AS
VARCHAR(50);

CREATE DOMAIN ENTERO AS
INTEGER;

CREATE DOMAIN FECHAHORA AS
TIMESTAMP;

CREATE DOMAIN GUID AS
VARCHAR(38);

CREATE DOMAIN IMAGEN AS
BLOB SUB_TYPE 0 SEGMENT SIZE 80;

CREATE DOMAIN MINIENTERO AS
SMALLINT;

CREATE DOMAIN "REAL" AS
DOUBLE PRECISION;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ABONOS (
    ID_ABONOS    GUID NOT NULL,
    FECHA_ABONO  FECHAHORA,
    PAGO         "REAL",
    ID_CLIENTES  GUID,
    LATITUD      "REAL",
    LONGITUD     "REAL"
);


CREATE TABLE ARTICULOS (
    ID_ARTICULOS  GUID NOT NULL,
    CODIGO        CADENA050,
    NOMBRE        CADENA050,
    COSTO         "REAL",
    PRECIO        "REAL",
    EXISTENCIA    ENTERO
);


CREATE TABLE CLIENTES (
    ID_CLIENTES       GUID NOT NULL,
    NUMERO_CLIENTE    ENTERO,
    NOMBRE            CADENA050,
    APELLIDO_PATERNO  CADENA050,
    APELLIDO_MATERNO  CADENA050,
    TELEFONO          CADENA010,
    CELULAR           CADENA010,
    CALLE             CADENA050,
    NUMERO_EXTERIOR   MINIENTERO,
    NUMERO_INTERIOR   MINIENTERO,
    COLONIA           CADENA050,
    LOCALIDAD         CADENA050,
    REFERENCIA        CADENA050,
    MUNICIPIO         CADENA050,
    ID_ESTADOS        GUID,
    CODIGO_POSTAL     ENTERO
);


CREATE TABLE ESTADOS (
    ID_ESTADOS  GUID NOT NULL,
    NOMBRE      CADENA050
);


CREATE TABLE VENTAS (
    ID_VENTAS    GUID NOT NULL,
    ID_CLIENTES  GUID,
    FOLIO        ENTERO,
    FECHA_VENTA  FECHAHORA
);


CREATE TABLE VENTAS_DETALLES (
    ID_VENTAS_DETALLES  GUID NOT NULL,
    ID_VENTAS           GUID,
    ID_ARTICULOS        GUID,
    COSTO               "REAL",
    PRECIO              "REAL"
);




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ABONOS ADD CONSTRAINT PK_ABONOS PRIMARY KEY (ID_ABONOS);
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (ID_ARTICULOS);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTES);
ALTER TABLE ESTADOS ADD CONSTRAINT PK_ESTADOS PRIMARY KEY (ID_ESTADOS);
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTAS);
ALTER TABLE VENTAS_DETALLES ADD CONSTRAINT PK_VENTAS_DETALLES PRIMARY KEY (ID_VENTAS_DETALLES);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE ABONOS ADD CONSTRAINT FK_ABONOS_1 FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES (ID_CLIENTES) ON UPDATE CASCADE;
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_1 FOREIGN KEY (ID_ESTADOS) REFERENCES ESTADOS (ID_ESTADOS);
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_1 FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES (ID_CLIENTES) ON UPDATE CASCADE;
ALTER TABLE VENTAS_DETALLES ADD CONSTRAINT FK_VENTAS_DETALLES_1 FOREIGN KEY (ID_VENTAS) REFERENCES VENTAS (ID_VENTAS) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE VENTAS_DETALLES ADD CONSTRAINT FK_VENTAS_DETALLES_2 FOREIGN KEY (ID_ARTICULOS) REFERENCES ARTICULOS (ID_ARTICULOS) ON UPDATE CASCADE;
